// Generated by CoffeeScript 1.3.3
(function() {

  Object.prototype = (function() {
    var proto;
    proto = Object.prototype;
    return proto.each = function(fn) {
      var key, _results;
      _results = [];
      for (key in this) {
        _results.push(fn(key));
      }
      return _results;
    };
  })();

}).call(this);
