// Generated by CoffeeScript 1.3.3
(function() {
  var _Number;

  _Number = Number.prototype;

  _Number.times = function(fn) {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = this.valueOf(); 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push(fn(i));
    }
    return _results;
  };

  _Number.odd = function() {
    return this.valueOf() % 2 !== 0;
  };

  _Number.multiple_of = _Number.multipleOf = function(n) {
    return n % this.valueOf() === 0;
  };

  _Number.min = _Number.mins = _Number.minute = _Number.minutes = function() {
    return this.valueOf() * 60;
  };

  _Number.hour = _Number.hours = function() {
    return this.valueOf() * 60..minutes();
  };

  _Number.day = _Number.days = function() {
    return this.valueOf() * 24..hours();
  };

  _Number.week = _Number.weeks = function() {
    return this.valueOf() * 7..days();
  };

  _Number.ago = function() {
    return Date.now().milli_to_sec() - this.valueOf();
  };

  _Number.milli_to_sec = _Number.milliToSeconds = function() {
    return parseInt(this.valueOf() / 1000);
  };

  _Number.sec_to_milli = _Number.secToMilli = function() {
    return this.valueOf() * 1000;
  };

  _Number.from_now = _Number.fromNow = function() {
    return Date.now().milli_to_sec() + this.valueOf();
  };

  _Number.to_d = _Number.to_date = _Number.toDate = function() {
    return new Date(this.valueOf().sec_to_milli());
  };

  _Number.days_in_month = _Number.daysInMonth = function() {
    var date;
    date = new Date();
    return new Date(date.getFullYear(), this.valueOf() + 1, 0).getDate();
  };

  _Number.days_in_month_of = _Number.daysInMonthOf = function(year) {
    return new Date(year, this.valueOf() + 1, 0).getDate();
  };

  _Number.days_in_month_of = _Number.daysInMonthOf = function(year) {
    return new Date(year, this.valueOf() + 1, 0).getDate();
  };

}).call(this);
